### ISSUE TITLE
React peer dependency

### ISSUE THREAD

**Issue by jurosh** [Olical/react-bodymovin#2]
Would be nice to increase React peer dependency, or at least support latest react.

To get rid of warnings:

```
npm WARN react-bodymovin@1.1.1 requires a peer of react@^15.3.0 but none was installed.
npm WARN react-bodymovin@1.1.1 requires a peer of react-dom@^15.3.0 but none was installed.
```

**Comment by Olical** [comment]
Yep, good point. I'll try to patch and release soon. I wonder if just `react@*` would be okay.

**Comment by jurosh** [comment]
Possibly yes, but question is if library is and will be functional with all React versions :)

Otherwise something like `"react": "^15.3.0 || ^16.0.0",` should be fine.

**Comment by Olical** [comment]
I would be extremely surprised if it didn't work since it's only a handful of lines and doesn't use much of React really. I'll set it to `*` so this doesn't come up again in the future. The peer dependency then just ensures that you have React somewhere, which should be fine.

**Comment by Olical** [comment]
Done, I should have done it way sooner though! Good suggestion.
