### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by nimaa77** [Olical/react-bodymovin#3]
hi, i was trying to analyze with webpack-bundle-analyzer and i saw some bad thing are happening.

when set BODYMOVIN_EXPRESSION_SUPPORT to true **bodymovin_light.min.js** and **bodymovin.min.js** files both loaded and this cause more **34K** file to bundle, i just fixed it by removing `BODYMOVIN_EXPRESSION_SUPPORT == null` but this not the right way to fix it. we have to set some default value for **BODYMOVIN_EXPRESSION_SUPPORT** variable, is there any way to set this ?

**Comment by Olical** [comment]
Hey there, sorry to hear that you're having issues. In the readme there's a snippet that configures this:

```js
plugins: ([
  new webpack.DefinePlugin({
    //Set true for the full bodymovin.min and false for bodymovin_light.min
    BODYMOVIN_EXPRESSION_SUPPORT: true
  })
])
```

But I don't think it's loading both instances. `bodymovin_light.min.js` _is_ 34k. Here's the table from the readme that I made a loooong time ago, but it's probably still correct. If it's too large for your use case you'll have to find another solution I'm afraid.

| Bodymovin file sizes | Normal | Light |
|----------------------|--------|-------|
| Default              | 492K   | 311K  |
| Minified             | 226K   | 129K  |
| Minified + Gzipped   | 53K    | 34K   |

**Comment by nimaa77** [comment]
while i set BODYMOVIN_EXPRESSION_SUPPORT to true
the bodymovin_light and bodymovin both loaded

i will send some screen shoots from **webpack-bundle-analyzer** in 2 hours and please, you give it a try yourself

**Comment by Olical** [comment]
I've pushed a branch called `conditional-light-cleanup`. If you check that branch out it might work a little better but I'd guess not. This was contributed by someone else, maybe it used to work and webpack changed so it doesn't work anymore.

The only other fix would be to change how the conditional switching works but I don't know if I want do right now. This is an old project and it's tiny. You could just fork it and delete the branching logic so you only include the light version?

**Comment by nimaa77** [comment]
### The Problem
when set 

    new webpack.DefinePlugin({
        // Set true for the full bodymovin.min and false for bodymovin_light.min
        BODYMOVIN_EXPRESSION_SUPPORT: JSON.stringify(true) 
      }),`
OR

    new webpack.DefinePlugin({
        // Set true for the full bodymovin.min and false for bodymovin_light.min
        BODYMOVIN_EXPRESSION_SUPPORT: true
      }),`

both **Normal** and **Light** files loaded, Even By Changing File Load Logic

![screenshot from 2018-10-03 01-48-49](https://user-images.githubusercontent.com/25016067/46381415-06c7c080-c6b3-11e8-867d-2c0107293e37.png)
Image From WebpackBundleAnalyzerPlugin

### The Problem
there is no default value for **BODYMOVIN_EXPRESSION_SUPPORT**
and we can't check if it equals to 'undefined' (even if it is set to true, false or not define it at all, while we compare it to undefined it returns true)

**Comment by nimaa77** [comment]
> I've pushed a branch called `conditional-light-cleanup`. If you check that branch out it might work a little better but I'd guess not. This was contributed by someone else, maybe it used to work and webpack changed so it doesn't work anymore.
> 
> The only other fix would be to change how the conditional switching works but I don't know if I want do right now. This is an old project and it's tiny. You could just fork it and delete the branching logic so you only include the light version?

**Comment by nimaa77** [comment]
> I've pushed a branch called `conditional-light-cleanup`. If you check that branch out it might work a little better but I'd guess not. This was contributed by someone else, maybe it used to work and webpack changed so it doesn't work anymore.
> 
> The only other fix would be to change how the conditional switching works but I don't know if I want do right now. This is an old project and it's tiny. You could just fork it and delete the branching logic so you only include the light version?

**Comment by nimaa77** [comment]
shit, i don't know how to deal with github :)

**Comment by Olical** [comment]
Haha, it's okay. So it looks like webpack will inline both requires no matter what, which honestly makes sense to me. The examples of conditional requires I've seen haven't convinced me. So I'd recommend you either modify this project and delete the code you don't want _or_ at some point I'll update the project so the requires work differently.

I wonder if I can have two files that you can import: `ReactBodymovin` and `ReactBodymovinFull`, that'd eliminate these issues pretty cleanly. Just requires shuffling code around as well as moving some shared code into `ReactBodymovinCore` or something. So it'll take the instance of bodymovin as an argument, like dependency injection.
