### ISSUE TITLE
window is not defined on SSR

### ISSUE THREAD

**Issue by nimahkh** [Olical/react-bodymovin#4]
Hello friends , 
thanks for your nice component , very useful and interesting .
i have a problem when i use this component with razzle . 

> window is not defined

**Comment by Olical** [comment]
I'm not sure what razzle is? Do you have any more context?

**Comment by nimahkh** [comment]
razzle is something like next.js

**Comment by Olical** [comment]
If it doesn't expose a window object I don't know what else I can do
really. It could just be a fault in how razzle sets up the DOM.

I haven't used any SSR tools so I'm not sure how they do things.

**Comment by Olical** [comment]
Yeah, I don't use window in an unsafe way in my code. So it's either body-movin (which I can't do anything about) or a bug elsewhere. I'm afraid I'm going to have to close this, there's nothing I can do as far as I can tell.
