### ISSUE TITLE
setting the speed with setSpeed?

### ISSUE THREAD

**Issue by Arthurgoujon** [Olical/react-bodymovin#5]
Is there a way to change the speed of the animation? I am trying to achieve the same result as this example in Javascript
https://codepen.io/chrisgannon/pen/yXmbMg

**Comment by Olical** [comment]
Sorry, I'm not sure and not maintaining this repository since I'm not involved in any frontend work whatsoever anymore. There's a good chance it's not possible at all through this library.

**Comment by Arthurgoujon** [comment]
Thank you, no worries at all. To get around it I moved on to another library: lottie-web
